### ISSUE TITLE
missing curl dependency

### ISSUE THREAD

**Issue by vsimko** [Eflores89/nasadata#3]
`jsonlite` fails if `curl` package is not installed

**Comment by Eflores89** [comment]
Thanks for the help. 

How do you get around this?

**Comment by Eflores89** [comment]
Also, i'm hessitant to update the .rd files because I have been documenting using `roxygen` and `devtools` to build. So I'm going to try to change them from the R source comments...

**Comment by vsimko** [comment]
I found the error when building on Travis. The fix was easy, I updated `DESCRIPTION` as follows:

```
Suggests:
    testthat,
    curl
```

(testthat is only for unit-testing)

**Comment by vsimko** [comment]
Regarding the `.Rd` files, I'm also using roxygen. All the changes were actually introduced by regenerating documentation using roxygen.
