### ISSUE TITLE
Get rid of global variables

### ISSUE THREAD

**Issue by vsimko** [Eflores89/nasadata#4]
I was really surprized to find `R/gvars.R`

**Comment by Eflores89** [comment]
Notes come up when doing `devtools::check()` about this. What do you suggest is best practice?

**Comment by vsimko** [comment]
I'm just trying to cleanup the implementation by removing all global variables.
First, I'm implementing the unit tests and then will clean it up.

Do you have any remarks that might be helpful?
Is there any special purpose for the globals that I cannot see ?

**Comment by Eflores89** [comment]
Nop. Basically I added them because of that note that keeps coming up. And read this: http://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when

**Comment by vsimko** [comment]
Ok, I'll let you know, when the implementation is ready

**Comment by vsimko** [comment]
it is ready
