### ISSUE TITLE
Does setting category_id override all the other parameters ?

### ISSUE THREAD

**Issue by vsimko** [Eflores89/nasadata#8]
In `R/eonet.R` the `query` variable is replaced even though it has already been filled with some data.
This happens when category_id is not "all".

``` r
if (category_id != "all") {
    # TODO: Previously constructed "s" gets replaced within this branch !!!!
    # Use Category API...
    cs <- eonet_categories()
    query <- cs[cs$id == category_id,]$link
    if (length(query) == 0) {
      stop("Category id is not valid. Review using eonet_categories()")
    }
  }
```

**Comment by Eflores89** [comment]
This is in the pull request I merged? Seems right...

**Comment by vsimko** [comment]
Yes, this is the current code. But the problem was also in the original code.
The point is that at the beginning of the function, there is some query construction happening which is then completely replaced if `category_id != "all"`.
As I was editing the file I didn't want to touch the logical structure of the code. I just spotted the potential problem and thus created this issue.

**Comment by Eflores89** [comment]
Yep, this is correct. When filtering by category for some reason a call to the other API is what's used, at least in the NASA docs...
